package chatgpt2api

// Code generated by scripts/generate_sdks.py. DO NOT EDIT.
//
// chatgpt2api Go SDK — 自动生成 (v2.24.0)
//
// 用法：
//     client := chatgpt2api.NewClient("/", "your-api-key")
//     models, err := client.ListModels()
//

import (
    "bytes"
    "encoding/json"
    "fmt"
    "io"
    "net/http"
    "net/url"
)

const Version = "2.24.0"

// Client 是 chatgpt2api 的 API 客户端
type Client struct {
    baseURL string
    apiKey  string
    http    *http.Client
}

// NewClient 创建一个新的 API 客户端
func NewClient(baseURL, apiKey string) *Client {
    return &Client{
        baseURL: baseURL,
        apiKey:  apiKey,
        http:    &http.Client{},
    }
}

func (c *Client) do(method, path string, body interface{}) ([]byte, error) {
    u, err := url.JoinPath(c.baseURL, path)
    if err != nil {
        return nil, fmt.Errorf("invalid URL: %w", err)
    }
    var reqBody io.Reader
    if body != nil {
        b, err := json.Marshal(body)
        if err != nil {
            return nil, fmt.Errorf("marshal body: %w", err)
        }
        reqBody = bytes.NewReader(b)
    }
    req, err := http.NewRequest(method, u, reqBody)
    if err != nil {
        return nil, fmt.Errorf("new request: %w", err)
    }
    req.Header.Set("Content-Type", "application/json")
    if c.apiKey != "" {
        req.Header.Set("Authorization", "Bearer "+c.apiKey)
    }
    resp, err := c.http.Do(req)
    if err != nil {
        return nil, fmt.Errorf("do request: %w", err)
    }
    defer resp.Body.Close()
    if resp.StatusCode >= 400 {
        bodyBytes, _ := io.ReadAll(resp.Body)
        return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(bodyBytes))
    }
    return io.ReadAll(resp.Body)
}

func (c *Client) doJSON(method, path string, body, result interface{}) error {
    b, err := c.do(method, path, body)
    if err != nil {
        return err
    }
    if result != nil {
        if err := json.Unmarshal(b, result); err != nil {
            return fmt.Errorf("unmarshal response: %w", err)
        }
    }
    return nil
}

// --- 数据模型 ---

type AccountBatchRequest struct {
    Action string `json:"action"`
    Ids []string `json:"ids"`
    Label string `json:"label"`
    Updates interface{} `json:"updates"`
}

type AccountCreateRequest struct {
    Tokens []string `json:"tokens"`
    Accounts []interface{} `json:"accounts"`
}

type AccountDeleteRequest struct {
    Tokens []string `json:"tokens"`
}

type AccountExportRequest struct {
    AccessTokens []string `json:"access_tokens"`
    Format string `json:"format"`
}

type AccountGroupRenameRequest struct {
    Action string `json:"action"`
    OldLabel string `json:"old_label"`
    NewLabel string `json:"new_label"`
}

type AccountRefreshRequest struct {
    AccessTokens []string `json:"access_tokens"`
}

type AccountUpdateRequest struct {
    AccessToken string `json:"access_token"`
    Type interface{} `json:"type"`
    Status interface{} `json:"status"`
    Quota interface{} `json:"quota"`
    Proxy interface{} `json:"proxy"`
}

type AnthropicMessageRequest struct {
    Model interface{} `json:"model"`
    Messages interface{} `json:"messages"`
    System interface{} `json:"system"`
    Stream interface{} `json:"stream"`
}

type BackupDeleteRequest struct {
    Key string `json:"key"`
}

type CPAImportRequest struct {
    Names []string `json:"names"`
}

type CPAPoolCreateRequest struct {
    Name string `json:"name"`
    BaseUrl string `json:"base_url"`
    SecretKey string `json:"secret_key"`
}

type CPAPoolUpdateRequest struct {
    Name interface{} `json:"name"`
    BaseUrl interface{} `json:"base_url"`
    SecretKey interface{} `json:"secret_key"`
}

type ChatCompletionRequest struct {
    Model interface{} `json:"model"`
    Prompt interface{} `json:"prompt"`
    N interface{} `json:"n"`
    Stream interface{} `json:"stream"`
    Modalities interface{} `json:"modalities"`
    Messages interface{} `json:"messages"`
}

type ClearanceTestRequest struct {
    TargetUrl string `json:"target_url"`
}

type EditableFileTaskRequest struct {
    Prompt string `json:"prompt"`
    Base64Images []string `json:"base64_images"`
    ClientTaskId interface{} `json:"client_task_id"`
}

type HTTPValidationError struct {
    Detail []interface{} `json:"detail"`
}

type ImageDeleteRequest struct {
    Paths []string `json:"paths"`
    StartDate string `json:"start_date"`
    EndDate string `json:"end_date"`
    AllMatching bool `json:"all_matching"`
}

type ImageDownloadRequest struct {
    Paths []string `json:"paths"`
}

type ImageGenerationRequest struct {
    Prompt string `json:"prompt"`
    Model string `json:"model"`
    N int `json:"n"`
    Size interface{} `json:"size"`
    Quality string `json:"quality"`
    ResponseFormat string `json:"response_format"`
    HistoryDisabled bool `json:"history_disabled"`
    Stream interface{} `json:"stream"`
}

type ImageGenerationTaskRequest struct {
    ClientTaskId string `json:"client_task_id"`
    Prompt string `json:"prompt"`
    Model string `json:"model"`
    Size interface{} `json:"size"`
    Quality string `json:"quality"`
    Seed interface{} `json:"seed"`
}

type ImageTagsRequest struct {
    Path string `json:"path"`
    Tags []string `json:"tags"`
}

type KeyCreateRequest struct {
    Name string `json:"name"`
    Role string `json:"role"`
    ExpiresAt interface{} `json:"expires_at"`
    Permissions interface{} `json:"permissions"`
    Quota interface{} `json:"quota"`
}

type KeyUpdateRequest struct {
    Name interface{} `json:"name"`
    Enabled interface{} `json:"enabled"`
    ExpiresAt interface{} `json:"expires_at"`
    Permissions interface{} `json:"permissions"`
    Quota interface{} `json:"quota"`
}

type KookeeyConfigRequest struct {
    Enabled bool `json:"enabled"`
    ExtractUrl string `json:"extract_url"`
    DeveloperToken string `json:"developer_token"`
    AccessId string `json:"access_id"`
    DefaultCountry string `json:"default_country"`
    DefaultCount int `json:"default_count"`
    SslVerify bool `json:"ssl_verify"`
    ProxyEnabled bool `json:"proxy_enabled"`
}

type KookeeyExtractRequest struct {
    Country string `json:"country"`
    Count int `json:"count"`
}

type LogDeleteRequest struct {
    Ids []string `json:"ids"`
}

type LogLevelRequest struct {
    Levels []string `json:"levels"`
}

type OAuthLoginFinishRequest struct {
    SessionId string `json:"session_id"`
    Callback string `json:"callback"`
}

type OAuthLoginStartRequest struct {
    EmailHint string `json:"email_hint"`
}

type ProxyAddRequest struct {
    Url string `json:"url"`
    Weight int `json:"weight"`
}

type ProxyBatchImportRequest struct {
    Text string `json:"text"`
    Weight int `json:"weight"`
}

type ProxyStrategyRequest struct {
    Strategy string `json:"strategy"`
}

type ProxyTestRequest struct {
    Url string `json:"url"`
}

type ProxyWeightRequest struct {
    Url string `json:"url"`
    Weight int `json:"weight"`
}

type ResponseCreateRequest struct {
    Model interface{} `json:"model"`
    Input interface{} `json:"input"`
    Tools interface{} `json:"tools"`
    ToolChoice interface{} `json:"tool_choice"`
    Stream interface{} `json:"stream"`
}

type ResumePollRequest struct {
    ExtraTimeoutSecs float64 `json:"extra_timeout_secs"`
}

type SearchRequest struct {
    Prompt string `json:"prompt"`
}

type SettingsUpdateRequest struct {
}

type Sub2APIImportRequest struct {
    AccountIds []string `json:"account_ids"`
}

type Sub2APIServerCreateRequest struct {
    Name string `json:"name"`
    BaseUrl string `json:"base_url"`
    Email string `json:"email"`
    Password string `json:"password"`
    ApiKey string `json:"api_key"`
    GroupId string `json:"group_id"`
}

type Sub2APIServerUpdateRequest struct {
    Name interface{} `json:"name"`
    BaseUrl interface{} `json:"base_url"`
    Email interface{} `json:"email"`
    Password interface{} `json:"password"`
    ApiKey interface{} `json:"api_key"`
    GroupId interface{} `json:"group_id"`
}

type UserKeyCreateRequest struct {
    Name string `json:"name"`
}

type UserKeyUpdateRequest struct {
    Name interface{} `json:"name"`
    Enabled interface{} `json:"enabled"`
    Key interface{} `json:"key"`
}

type ValidationError struct {
    Loc []interface{} `json:"loc"`
    Msg string `json:"msg"`
    Type string `json:"type"`
    Input interface{} `json:"input"`
    Ctx interface{} `json:"ctx"`
}

// --- API 方法 ---

// AI
// List Models
func (c *Client) ListModelsV1ModelsGet(c *Client) ([]byte, error) {
    return c.do("GET", "/v1/models", nil)
}

// Generate Images
func (c *Client) GenerateImagesV1ImagesGenerationsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/v1/images/generations", body)
}

// Edit Images
func (c *Client) EditImagesV1ImagesEditsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/v1/images/edits", nil)
}

// Create Chat Completion
func (c *Client) CreateChatCompletionV1ChatCompletionsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/v1/chat/completions", body)
}

// Create Response
func (c *Client) CreateResponseV1ResponsesPost(c *Client) ([]byte, error) {
    return c.do("POST", "/v1/responses", body)
}

// Create Message
func (c *Client) CreateMessageV1MessagesPost(c *Client) ([]byte, error) {
    return c.do("POST", "/v1/messages", body)
}

// Search
func (c *Client) SearchV1SearchPost(c *Client) ([]byte, error) {
    return c.do("POST", "/v1/search", body)
}

// List Editable File Tasks
func (c *Client) ListEditableFileTasksV1EditableFileTasksGet(c *Client) ([]byte, error) {
    return c.do("GET", "/v1/editable-file-tasks", nil)
}

// Download Editable File
func (c *Client) DownloadEditableFileFilesFilePathGet(c *Client, file_path string) ([]byte, error) {
    return c.do("GET", "/files/" + file_path + "", nil)
}

// Create Ppt Task
func (c *Client) CreatePptTaskV1PptGenerationsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/v1/ppt/generations", body)
}

// Create Psd Task
func (c *Client) CreatePsdTaskV1PsdGenerationsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/v1/psd/generations", body)
}

// Accounts
// List User Keys
func (c *Client) ListUserKeysApiAuthUsersGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/auth/users", nil)
}

// Create User Key
func (c *Client) CreateUserKeyApiAuthUsersPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/auth/users", body)
}

// Update User Key
func (c *Client) UpdateUserKeyApiAuthUsersKeyIdPost(c *Client, key_id string) ([]byte, error) {
    return c.do("POST", "/api/auth/users/" + key_id + "", body)
}

// Delete User Key
func (c *Client) DeleteUserKeyApiAuthUsersKeyIdDelete(c *Client, key_id string) ([]byte, error) {
    return c.do("DELETE", "/api/auth/users/" + key_id + "", nil)
}

// Get Accounts
func (c *Client) GetAccountsApiAccountsGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/accounts", nil)
}

// Create Accounts
func (c *Client) CreateAccountsApiAccountsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/accounts", body)
}

// Delete Accounts
func (c *Client) DeleteAccountsApiAccountsDelete(c *Client) ([]byte, error) {
    return c.do("DELETE", "/api/accounts", body)
}

// Refresh Accounts
func (c *Client) RefreshAccountsApiAccountsRefreshPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/accounts/refresh", body)
}

// Get Refresh Progress
func (c *Client) GetRefreshProgressApiAccountsRefreshProgressProgressIdGet(c *Client, progress_id string) ([]byte, error) {
    return c.do("GET", "/api/accounts/refresh/progress/" + progress_id + "", nil)
}

// Re Login Accounts
func (c *Client) ReLoginAccountsApiAccountsReLoginPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/accounts/re-login", body)
}

// Get Relogin Progress
func (c *Client) GetReloginProgressApiAccountsReLoginProgressProgressIdGet(c *Client, progress_id string) ([]byte, error) {
    return c.do("GET", "/api/accounts/re-login/progress/" + progress_id + "", nil)
}

// Recover Abnormal Accounts
func (c *Client) RecoverAbnormalAccountsApiAccountsRecoverPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/accounts/recover", body)
}

// Evict Stale Accounts
func (c *Client) EvictStaleAccountsApiAccountsEvictStalePost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/accounts/evict_stale", nil)
}

// Export Accounts
func (c *Client) ExportAccountsApiAccountsExportPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/accounts/export", body)
}

// Batch Accounts
func (c *Client) BatchAccountsApiAccountsBatchPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/accounts/batch", body)
}

// Get Account Groups
func (c *Client) GetAccountGroupsApiAccountsGroupsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/accounts/groups", body)
}

// Update Account
func (c *Client) UpdateAccountApiAccountsUpdatePost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/accounts/update", body)
}

// Start Oauth Login
func (c *Client) StartOauthLoginApiAccountsOauthStartPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/accounts/oauth/start", body)
}

// Finish Oauth Login
func (c *Client) FinishOauthLoginApiAccountsOauthFinishPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/accounts/oauth/finish", body)
}

// Get Account Health Scores
func (c *Client) GetAccountHealthScoresApiAccountsHealthScoresGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/accounts/health-scores", nil)
}

// List Cpa Pools
func (c *Client) ListCpaPoolsApiCpaPoolsGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/cpa/pools", nil)
}

// Create Cpa Pool
func (c *Client) CreateCpaPoolApiCpaPoolsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/cpa/pools", body)
}

// Update Cpa Pool
func (c *Client) UpdateCpaPoolApiCpaPoolsPoolIdPost(c *Client, pool_id string) ([]byte, error) {
    return c.do("POST", "/api/cpa/pools/" + pool_id + "", body)
}

// Delete Cpa Pool
func (c *Client) DeleteCpaPoolApiCpaPoolsPoolIdDelete(c *Client, pool_id string) ([]byte, error) {
    return c.do("DELETE", "/api/cpa/pools/" + pool_id + "", nil)
}

// Cpa Pool Files
func (c *Client) CpaPoolFilesApiCpaPoolsPoolIdFilesGet(c *Client, pool_id string) ([]byte, error) {
    return c.do("GET", "/api/cpa/pools/" + pool_id + "/files", nil)
}

// Cpa Pool Import Progress
func (c *Client) CpaPoolImportProgressApiCpaPoolsPoolIdImportGet(c *Client, pool_id string) ([]byte, error) {
    return c.do("GET", "/api/cpa/pools/" + pool_id + "/import", nil)
}

// Cpa Pool Import
func (c *Client) CpaPoolImportApiCpaPoolsPoolIdImportPost(c *Client, pool_id string) ([]byte, error) {
    return c.do("POST", "/api/cpa/pools/" + pool_id + "/import", body)
}

// List Sub2Api Servers
func (c *Client) ListSub2ApiServersApiSub2ApiServersGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/sub2api/servers", nil)
}

// Create Sub2Api Server
func (c *Client) CreateSub2ApiServerApiSub2ApiServersPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/sub2api/servers", body)
}

// Update Sub2Api Server
func (c *Client) UpdateSub2ApiServerApiSub2ApiServersServerIdPost(c *Client, server_id string) ([]byte, error) {
    return c.do("POST", "/api/sub2api/servers/" + server_id + "", body)
}

// Delete Sub2Api Server
func (c *Client) DeleteSub2ApiServerApiSub2ApiServersServerIdDelete(c *Client, server_id string) ([]byte, error) {
    return c.do("DELETE", "/api/sub2api/servers/" + server_id + "", nil)
}

// Sub2Api Server Groups
func (c *Client) Sub2ApiServerGroupsApiSub2ApiServersServerIdGroupsGet(c *Client, server_id string) ([]byte, error) {
    return c.do("GET", "/api/sub2api/servers/" + server_id + "/groups", nil)
}

// Sub2Api Server Accounts
func (c *Client) Sub2ApiServerAccountsApiSub2ApiServersServerIdAccountsGet(c *Client, server_id string) ([]byte, error) {
    return c.do("GET", "/api/sub2api/servers/" + server_id + "/accounts", nil)
}

// Sub2Api Server Import Progress
func (c *Client) Sub2ApiServerImportProgressApiSub2ApiServersServerIdImportGet(c *Client, server_id string) ([]byte, error) {
    return c.do("GET", "/api/sub2api/servers/" + server_id + "/import", nil)
}

// Sub2Api Server Import
func (c *Client) Sub2ApiServerImportApiSub2ApiServersServerIdImportPost(c *Client, server_id string) ([]byte, error) {
    return c.do("POST", "/api/sub2api/servers/" + server_id + "/import", body)
}

// Auth Keys
// List Keys
func (c *Client) ListKeysApiAuthKeysGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/auth/keys", nil)
}

// Create Key
func (c *Client) CreateKeyApiAuthKeysPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/auth/keys", body)
}

// Update Key
func (c *Client) UpdateKeyApiAuthKeysKeyIdPost(c *Client, key_id string) ([]byte, error) {
    return c.do("POST", "/api/auth/keys/" + key_id + "", body)
}

// Delete Key
func (c *Client) DeleteKeyApiAuthKeysKeyIdDelete(c *Client, key_id string) ([]byte, error) {
    return c.do("DELETE", "/api/auth/keys/" + key_id + "", nil)
}

// Revoke Key
func (c *Client) RevokeKeyApiAuthKeysKeyIdRevokePost(c *Client, key_id string) ([]byte, error) {
    return c.do("POST", "/api/auth/keys/" + key_id + "/revoke", nil)
}

// Get Key Usage
func (c *Client) GetKeyUsageApiAuthKeysUsageGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/auth/keys/usage", nil)
}

// Dashboard
// Scheduler Dashboard
func (c *Client) SchedulerDashboardApiDashboardSchedulerGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/dashboard/scheduler", nil)
}

// Circuit Breakers
func (c *Client) CircuitBreakersApiDashboardCircuitBreakersGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/dashboard/circuit_breakers", nil)
}

// Ops Overview
func (c *Client) OpsOverviewApiDashboardOpsGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/dashboard/ops", nil)
}

// Usage Stats
func (c *Client) UsageStatsApiDashboardUsageGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/dashboard/usage", nil)
}

// Usage Totals
func (c *Client) UsageTotalsApiDashboardUsageTotalsGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/dashboard/usage-totals", nil)
}

// Usage Forecast Stats
func (c *Client) UsageForecastStatsApiDashboardUsageForecastGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/dashboard/usage-forecast", nil)
}

// Quota Detail
func (c *Client) QuotaDetailApiDashboardQuotaGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/dashboard/quota", nil)
}

// Capacity Stats
func (c *Client) CapacityStatsApiDashboardCapacityGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/dashboard/capacity", nil)
}

// Latency Stats
func (c *Client) LatencyStatsApiDashboardLatencyGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/dashboard/latency", nil)
}

// Metrics Summary
func (c *Client) MetricsSummaryApiDashboardMetricsSummaryGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/dashboard/metrics_summary", nil)
}

// Adaptive Scheduler Status
func (c *Client) AdaptiveSchedulerStatusApiDashboardAdaptiveSchedulerGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/dashboard/adaptive_scheduler", nil)
}

// Image Tasks
// List Image Tasks
func (c *Client) ListImageTasksApiImageTasksGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/image-tasks", nil)
}

// Create Generation Task
func (c *Client) CreateGenerationTaskApiImageTasksGenerationsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/image-tasks/generations", body)
}

// Create Edit Task
func (c *Client) CreateEditTaskApiImageTasksEditsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/image-tasks/edits", nil)
}

// Resume Image Poll
func (c *Client) ResumeImagePollApiImageTasksTaskIdResumePollPost(c *Client, task_id string) ([]byte, error) {
    return c.do("POST", "/api/image-tasks/" + task_id + "/resume-poll", body)
}

// Kookeey
// Get Kookeey Config
func (c *Client) GetKookeeyConfigApiKookeeyConfigGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/kookeey/config", nil)
}

// Update Kookeey Config
func (c *Client) UpdateKookeeyConfigApiKookeeyConfigPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/kookeey/config", body)
}

// Get Kookeey Stats
func (c *Client) GetKookeeyStatsApiKookeeyStatsGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/kookeey/stats", nil)
}

// Test Kookeey
func (c *Client) TestKookeeyApiKookeeyTestPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/kookeey/test", nil)
}

// Extract Kookeey
func (c *Client) ExtractKookeeyApiKookeeyExtractPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/kookeey/extract", body)
}

// Get Kookeey Traffic
func (c *Client) GetKookeeyTrafficApiKookeeyTrafficGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/kookeey/traffic", nil)
}

// Get Kookeey Balance
func (c *Client) GetKookeeyBalanceApiKookeeyBalanceGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/kookeey/balance", nil)
}

// Get Kookeey Traffic Detail
func (c *Client) GetKookeeyTrafficDetailApiKookeeyTrafficDetailGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/kookeey/traffic-detail", nil)
}

// Get Kookeey Ip Usage
func (c *Client) GetKookeeyIpUsageApiKookeeyIpUsageGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/kookeey/ip-usage", nil)
}

// Probe Kookeey Ips
func (c *Client) ProbeKookeeyIpsApiKookeeyProbeIpsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/kookeey/probe-ips", nil)
}

// Providers
// Get Providers
func (c *Client) GetProvidersApiProvidersGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/providers", nil)
}

// Proxy Pool
// List Proxies
func (c *Client) ListProxiesApiProxiesGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/proxies", nil)
}

// Add Proxy
func (c *Client) AddProxyApiProxiesPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/proxies", body)
}

// Batch Import Proxies
func (c *Client) BatchImportProxiesApiProxiesBatchImportPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/proxies/batch-import", body)
}

// Remove Proxy
func (c *Client) RemoveProxyApiProxiesUrlDelete(c *Client, url string) ([]byte, error) {
    return c.do("DELETE", "/api/proxies/" + url + "", nil)
}

// Update Weight
func (c *Client) UpdateWeightApiProxiesWeightPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/proxies/weight", body)
}

// Set Strategy
func (c *Client) SetStrategyApiProxiesStrategyPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/proxies/strategy", body)
}

// Trigger Health Check
func (c *Client) TriggerHealthCheckApiProxiesHealthCheckPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/proxies/health-check", nil)
}

// Probe Kookeey Egress
func (c *Client) ProbeKookeeyEgressApiProxiesKookeeyEgressPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/proxies/kookeey-egress", body)
}

// Probe Egress Ip
func (c *Client) ProbeEgressIpApiProxiesProbeIpPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/proxies/probe-ip", body)
}

// Get Egress Ip
func (c *Client) GetEgressIpApiProxiesEgressIpGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/proxies/egress-ip", nil)
}

// System
// Login
func (c *Client) LoginAuthLoginPost(c *Client) ([]byte, error) {
    return c.do("POST", "/auth/login", nil)
}

// Get Version
func (c *Client) GetVersionVersionGet(c *Client) ([]byte, error) {
    return c.do("GET", "/version", nil)
}

// Health Ready
func (c *Client) HealthReadyApiSystemHealthReadyGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/system/health/ready", nil)
}

// Get Settings
func (c *Client) GetSettingsApiSettingsGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/settings", nil)
}

// Save Settings
func (c *Client) SaveSettingsApiSettingsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/settings", body)
}

// Get Images
func (c *Client) GetImagesApiImagesGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/images", nil)
}

// Delete Images Endpoint
func (c *Client) DeleteImagesEndpointApiImagesDeletePost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/images/delete", body)
}

// Download Images Endpoint
func (c *Client) DownloadImagesEndpointApiImagesDownloadPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/images/download", body)
}

// Download Single Image Endpoint
func (c *Client) DownloadSingleImageEndpointApiImagesDownloadImagePathGet(c *Client, image_path string) ([]byte, error) {
    return c.do("GET", "/api/images/download/" + image_path + "", nil)
}

// Proxy Download Image Endpoint
func (c *Client) ProxyDownloadImageEndpointApiImagesProxyDownloadGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/images/proxy-download", nil)
}

// Get Logs
func (c *Client) GetLogsApiLogsGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/logs", nil)
}

// Delete Logs
func (c *Client) DeleteLogsApiLogsDeletePost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/logs/delete", body)
}

// Get Log Level
func (c *Client) GetLogLevelApiSystemLogLevelGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/system/log-level", nil)
}

// Set Log Level
func (c *Client) SetLogLevelApiSystemLogLevelPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/system/log-level", body)
}

// Get Audit
func (c *Client) GetAuditApiAuditGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/audit", nil)
}

// Export Audit Csv
func (c *Client) ExportAuditCsvApiAuditExportGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/audit/export", nil)
}

// Test Proxy Endpoint
func (c *Client) TestProxyEndpointApiProxyTestPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/proxy/test", body)
}

// Get Proxy Runtime Endpoint
func (c *Client) GetProxyRuntimeEndpointApiProxyRuntimeGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/proxy/runtime", nil)
}

// Save Proxy Runtime Endpoint
func (c *Client) SaveProxyRuntimeEndpointApiProxyRuntimePost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/proxy/runtime", body)
}

// Test Proxy Clearance Endpoint
func (c *Client) TestProxyClearanceEndpointApiProxyClearanceTestPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/proxy/clearance/test", body)
}

// Get Storage Info
func (c *Client) GetStorageInfoApiStorageInfoGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/storage/info", nil)
}

// Test Backup Connection
func (c *Client) TestBackupConnectionApiBackupTestPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/backup/test", nil)
}

// Test Image Storage Endpoint
func (c *Client) TestImageStorageEndpointApiImageStorageTestPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/image-storage/test", nil)
}

// Sync Image Storage Endpoint
func (c *Client) SyncImageStorageEndpointApiImageStorageSyncPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/image-storage/sync", nil)
}

// Get Backups
func (c *Client) GetBackupsApiBackupsGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/backups", nil)
}

// Run Backup Endpoint
func (c *Client) RunBackupEndpointApiBackupsRunPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/backups/run", nil)
}

// Delete Backup Endpoint
func (c *Client) DeleteBackupEndpointApiBackupsDeletePost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/backups/delete", body)
}

// Get Backup Detail
func (c *Client) GetBackupDetailApiBackupsDetailGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/backups/detail", nil)
}

// Download Backup Endpoint
func (c *Client) DownloadBackupEndpointApiBackupsDownloadGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/backups/download", nil)
}

// List Image Tags
func (c *Client) ListImageTagsApiImagesTagsGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/images/tags", nil)
}

// Update Image Tags
func (c *Client) UpdateImageTagsApiImagesTagsPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/images/tags", body)
}

// Delete Image Tag
func (c *Client) DeleteImageTagApiImagesTagsTagDelete(c *Client, tag string) ([]byte, error) {
    return c.do("DELETE", "/api/images/tags/" + tag + "", nil)
}

// Get Image Storage
func (c *Client) GetImageStorageApiImagesStorageGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/images/storage", nil)
}

// Compress All Images
func (c *Client) CompressAllImagesApiImagesStorageCompressPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/images/storage/compress", nil)
}

// Cleanup To Target
func (c *Client) CleanupToTargetApiImagesStorageCleanupToTargetPost(c *Client) ([]byte, error) {
    return c.do("POST", "/api/images/storage/cleanup-to-target", nil)
}

// Health Dashboard
func (c *Client) HealthDashboardHealthGet(c *Client) ([]byte, error) {
    return c.do("GET", "/health", nil)
}

// logs
// Aggregate Logs
func (c *Client) AggregateLogsApiLogsAggregateGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/logs/aggregate", nil)
}

// Export Logs
func (c *Client) ExportLogsApiLogsExportGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/logs/export", nil)
}

// Slow Queries
func (c *Client) SlowQueriesApiLogsSlowQueriesGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/logs/slow-queries", nil)
}

// tracing
// Get Traces
func (c *Client) GetTracesApiTracingTracesGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/tracing/traces", nil)
}

// Get Tracing Stats
func (c *Client) GetTracingStatsApiTracingStatsGet(c *Client) ([]byte, error) {
    return c.do("GET", "/api/tracing/stats", nil)
}
